### PR TITLE
Update language map, make terminology consistent

### PR DESCRIPTION
**Pull request by rbergen**
This adds a few additional entries to the language map, for languages that have recently been added or may be in the near future.
Also, the use of the term "language" is now uniformly apply within the codebase.

### CODE REVIEW

**Comment by marghidanu** [comment]
Let's have a small list for the terminology:

* Language: Programing language
* Implementation: A combination of language and solution number something like crystal-1, python-3, etc.

**Comment by rbergen** [comment]
I agree with the concept, but I think we need to work on the actual terminology. I'd propose the following:

- Language: Programming language
- Solution: A combination of language and solution number something like crystal-1, python-3, etc.
- Implementation: Approach to running the sieve. Each solution contains at least one implementation, but quite a few now contain multiple. One way to phrase it is that each implementation generates its own line in the drag-race output format,

**Comment by rbergen** [comment]
@marghidanu As we agree on the one term that matters for this PR (language), I would like to proceed with merging this, if there are no (other) review remarks.

**Comment by marghidanu** [comment]
LGTM

**Pull request merged**
